// Code generated by argsgen.
// DO NOT EDIT!

package options

import "flag"

func (o *options) Parse() {
	flag.StringVar(&o.i, "i", o.i, "input filename")
	flag.StringVar(&o.input, "input", o.i, "input filename")
	flag.StringVar(&o.o, "o", o.o, "output filename")
	flag.StringVar(&o.output, "output", o.o, "output filename")
	flag.StringVar(&o.db, "db", o.db, "database name")
	flag.StringVar(&o.database, "database", o.db, "database name")
	flag.StringVar(&o.folder, "folder", o.folder, "target folder")
	flag.UintVar(&o.parallel, "parallel", o.parallel, "number of process in parallel")
	flag.BoolVar(&o.profile, "profile", o.profile, "")
	flag.Parse()

	narg := flag.NArg()
	if narg == 0 {
		return
	}
	if narg != 2 {
		panic("not enough positional arguments found")
	}

	o.i = flag.Arg(0)
	o.input = flag.Arg(0)
	o.o = flag.Arg(1)
	o.output = flag.Arg(1)
}
